# Site settings
title: CausaliTea
tag_text: CausaliTea
description: Reading group about causality, held in the UCL Statistical Science Department.
# baseurl:
# url: "causaliteatalks.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
